version: '3.7'

services:

  backend:
    image: codegarden-stackdemo
    container_name: codegarden-stackdemo
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - .env:/app/.env
    ports:
    - 3000:3000
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  redis:
    image: redis
    command: "redis-server --appendonly yes"
    ports:
    - 6379:6379
    volumes:
    - ./redis-data:/data

